basic_symbols <- function() {
  symbols <- c(
    "AA", "ABLT", "ACH", "ADES",
    "AEM", "AGFS", "AKG", "AKZOY",
    "ALB", "AMCR", "AMRS", "AP",
    "APD", "ARD", "ARNC", "ASH",
    "ASIX", "ATI", "ATR", "AU", 
    "AUY", "AVD", "AVY", "AWCMY",
    "AXTA", "AYSI", "BAK", "BASFY",
    "BCC", "BCPC", "BERY", "BHP", 
    "BLL", "BVN", "CAEN", "CBT",
    "CC", "CCF", "CCK", "CDE",
    "CE", "CENX", "CF", "CGA",
    "CHNR", "CINR", "CLF", "CLW",
    "CMC", "CMCL", "CMP", "CMT", 
    "CPAC", "CRH", "CRS", "CSTM",
    "CTGO", "CTRA", "CTVA", "CX",
    "DD", "DOW", "DRD", "ECL",
    "EGO", "EMN", "ESI", "EXK",
    "EXP", "FCREY", "FCX", "FF",
    "FFHL", "FMC", "FOE", "FRD", 
    "FRTA", "FSI", "FTK", "FUL",
    "GBGD", "GCP", "GEF", "GFI",
    "GGB", "GLGI", "GLT", "GOLD", 
    "GORO", "GPK", "GRA", "GSS",
    "GURE", "HAYN", "HCC", "HCMLY",
    "HHT","HL","HMY","HUN","HWKN",
    "HYDI", "IAG", "IFF", "IKNX", 
    "IOSP","IP", "IPI", "ITP",
    "JHX","KALU","KEWL","KGC", 
    "KOP", "KRA", "NEXA", "NG",
    "KRO","KWR","LIN","LOOP",
    "LPX", "LTHM","LUNMF","LWLG",
    "LXU","LYB", "MAG","MBII",
    "MCEM","MEOH","MERC","METC", 
    "MLM", "MOS","MSB","MT",
    "MTL","MTRN", "MTX","MUX",
    "MYE","NAK","NEM","NEU",
    "NGD","NGVT","NHYDY","NINK",
    "NP","NTIC", "NUE","OEC",
    "OI","OLN","OPGX","OR",
    "OSN","PAAS", "PACK",
    "PGVI","PKG","PKX","PLTYF",
    "POL", "POPE","PPG","PQG",
    "PZG","RBTK", "RBYCF","RDSMY",
    "RETO","RFP", "RGLD","RIO",
    "RPM","RRIF","RS", "RYAM",
    "RYI","SA","SCCO","SCHN", 
    "SCL","SEE","SHI","SHW",
    "SID","SIM", "SINC","SLGN",
    "SMG","SMID", "ZKIN","STLD",
    "SMSMY","SON", "SPPJY","SQM",
    "SSL","SSRM", "WRK","WEBC",
    "SUM","SVM","SWM","SXC",
    "SXT", "SYNL","TANH","TECK",
    "TG","TGLS","TMRC", "TMST",
    "TORM","TREC","TROX", "TRX",
    "TSE","TX","UAN","UFPT",
    "UFS", "USAP","USAU","USCR",
    "USLM","VALE","VEDL", "VGZ",
    "VHI","VKSC","VMC","VNTR",
    "VRS", "VVV","WBRBY","WLK",
    "WLKP", "WMSI","WOR","WPM",
    "X","ZCOM", "ZEUS","ZGSI"
  )
}